name: my-ossetia-tour

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-ossetia-tour:latest
    restart: unless-stopped
    env_file:
      - ./deploy/.env.production
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${TRAEFIK_NETWORK}"
      - "traefik.http.routers.my-ossetia-tour.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.my-ossetia-tour.entrypoints=websecure"
      - "traefik.http.routers.my-ossetia-tour.tls.certresolver=le"
      - "traefik.http.services.my-ossetia-tour.loadbalancer.server.port=80"

networks:
  proxy:
    external: true
    name: ${TRAEFIK_NETWORK}
