-- Enable extensions
create extension if not exists pgcrypto;

-- Leads
create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  source_page text not null,
  tour_id bigint null references public.tours(id) on delete set null,
  name text not null,
  phone text not null,
  message text null,
  status text not null default 'new' check (status in ('new', 'in_progress', 'booked', 'closed_lost')),
  manager_comment text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Tours
create table if not exists public.tours (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  title text not null,
  short_description text not null,
  full_description text not null,
  price_from text not null,
  duration text not null,
  group_size text not null,
  location text not null,
  cover_image_url text not null,
  gallery text[] not null default '{}',
  is_published boolean not null default true,
  sort_order int not null default 0,
  seo_title text not null,
  seo_description text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Program items
create table if not exists public.tour_program_items (
  id bigint generated by default as identity primary key,
  tour_id bigint not null references public.tours(id) on delete cascade,
  position int not null default 0,
  title text not null,
  description text not null,
  image_url text not null,
  created_at timestamptz not null default now()
);

-- Home singleton
create table if not exists public.home_content (
  id int primary key default 1,
  hero_title text not null,
  hero_subtitle text not null,
  hero_image_url text not null,
  featured_tour_ids bigint[] not null default '{}',
  cta_title text not null,
  cta_text text not null,
  cta_primary_label text not null,
  cta_primary_url text not null,
  cta_secondary_label text not null,
  cta_secondary_url text not null,
  updated_at timestamptz not null default now()
);

insert into public.home_content (
  id,
  hero_title,
  hero_subtitle,
  hero_image_url,
  featured_tour_ids,
  cta_title,
  cta_text,
  cta_primary_label,
  cta_primary_url,
  cta_secondary_label,
  cta_secondary_url
)
values
(
  1,
  'Explore Ossetia with Local Guides',
  'Author routes through mountains, history and authentic places.',
  '/12476587.jpg',
  '{}',
  'Ready for your next route?',
  'Send request and we will prepare a custom trip for your dates.',
  'View tours',
  '/tours',
  'Contacts',
  '/contacts'
)
on conflict (id) do nothing;

-- updated_at trigger
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_updated_at_leads on public.leads;
create trigger set_updated_at_leads
before update on public.leads
for each row execute function public.set_updated_at();

drop trigger if exists set_updated_at_tours on public.tours;
create trigger set_updated_at_tours
before update on public.tours
for each row execute function public.set_updated_at();

drop trigger if exists set_updated_at_home on public.home_content;
create trigger set_updated_at_home
before update on public.home_content
for each row execute function public.set_updated_at();

-- RLS
alter table public.leads enable row level security;
alter table public.tours enable row level security;
alter table public.tour_program_items enable row level security;
alter table public.home_content enable row level security;

-- Public read policies
drop policy if exists "public read tours" on public.tours;
create policy "public read tours"
on public.tours for select
using (is_published = true);

drop policy if exists "public read tour items" on public.tour_program_items;
create policy "public read tour items"
on public.tour_program_items for select
using (exists (
  select 1 from public.tours t where t.id = tour_program_items.tour_id and t.is_published = true
));

drop policy if exists "public read home content" on public.home_content;
create policy "public read home content"
on public.home_content for select
using (true);

-- Authenticated admin policies via app_metadata role
drop policy if exists "admin full leads" on public.leads;
create policy "admin full leads"
on public.leads for all
using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists "admin full tours" on public.tours;
create policy "admin full tours"
on public.tours for all
using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists "admin full tour items" on public.tour_program_items;
create policy "admin full tour items"
on public.tour_program_items for all
using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists "admin full home" on public.home_content;
create policy "admin full home"
on public.home_content for all
using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

-- Public insert leads
drop policy if exists "public insert leads" on public.leads;
create policy "public insert leads"
on public.leads for insert
with check (true);

-- Storage
insert into storage.buckets (id, name, public)
values ('crm-media', 'crm-media', true)
on conflict (id) do nothing;

drop policy if exists "public read crm media" on storage.objects;
create policy "public read crm media"
on storage.objects for select
using (bucket_id = 'crm-media');

drop policy if exists "admin upload crm media" on storage.objects;
create policy "admin upload crm media"
on storage.objects for insert
with check (bucket_id = 'crm-media' and (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists "admin update crm media" on storage.objects;
create policy "admin update crm media"
on storage.objects for update
using (bucket_id = 'crm-media' and (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists "admin delete crm media" on storage.objects;
create policy "admin delete crm media"
on storage.objects for delete
using (bucket_id = 'crm-media' and (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');
