-- Create lead_stages table
create table if not exists public.lead_stages (
  id bigint generated by default as identity primary key,
  title text not null,
  sort_order int not null default 0,
  color text not null default '#78716c', -- Stone 500
  created_at timestamptz not null default now()
);

-- Initial stages
insert into public.lead_stages (title, sort_order, color)
values 
('Новая заявка', 1, '#3b82f6'), -- Blue 500
('В работе', 2, '#f59e0b'),     -- Amber 500
('Забронирован', 3, '#10b981'),  -- Emerald 500
('Потерян', 4, '#ef4444');      -- Red 500

-- Add stage_id to leads
alter table public.leads add column if not exists stage_id bigint references public.lead_stages(id);

-- Migrate existing status to stage_id
do $$
begin
  update public.leads set stage_id = (select id from public.lead_stages where title = 'Новая заявка') where status = 'new';
  update public.leads set stage_id = (select id from public.lead_stages where title = 'В работе') where status = 'in_progress';
  update public.leads set stage_id = (select id from public.lead_stages where title = 'Забронирован') where status = 'booked';
  update public.leads set stage_id = (select id from public.lead_stages where title = 'Потерян') where status = 'closed_lost';
end $$;

-- Make stage_id not null after migration for consistency
-- alter table public.leads alter column stage_id set not null; -- Maybe keep it nullable for safety during transition

-- Drop the old validation check from status field to allow flexibility, 
-- but keep the field for now to avoid breaking existing queries from other places if any.
alter table public.leads drop constraint if exists leads_status_check;

-- RLS for lead_stages
alter table public.lead_stages enable row level security;

drop policy if exists "admin full lead_stages" on public.lead_stages;
create policy "admin full lead_stages"
on public.lead_stages for all
using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');
